plugins {
    id 'com.android.application'
}

android {
    namespace 'com.growshopsluis.lightmeter'
    compileSdk 34

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        applicationId 'com.growshopsluis.lightmeter'
        minSdk 26
        targetSdk 34
        versionCode 8
        versionName '1.5.1'

    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.core:core:1.13.1'
    implementation 'androidx.work:work-runtime:2.9.1'
    testImplementation 'junit:junit:4.13.2'
}
